wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.27.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1786953441
    t:
      1:
      - 1
      - 12
      - 49
      - 51
      2:
      - 1
      - 12
      - 49
      - 51
      3:
      - 2
      - 3
      - 4
      - 13
      - 14
      - 16
      - 42
      4: 3.12.7
      5: 0.27.0
      13: linux-x86_64
    e:
      ppqslybakwfb4bu9tj32ly2pg1dsqe06:
        os: Linux-5.14.0-570.116.1.el9_6.x86_64-x86_64-with-glibc2.34
        python: CPython 3.12.7
        started_at: '2026-08-17T07:57:12.700203Z'
        program: -m experiments.train_flow
        root: /lustre/fsn1/projects/rech/prk/ugd35xy/pshear/cosmos
        host: r7i0n2
        executable: /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/python-3.12.7/bin/python
        cpu_count: 40
        cpu_count_logical: 80
        gpu_type: Tesla V100-SXM2-32GB
        gpu_count: 4
        disk:
          /:
            total: '100275138560'
            used: '9934614528'
        memory:
          total: '200550277120'
        gpu_nvidia:
        - name: Tesla V100-SXM2-32GB
          memory_total: '34359738368'
          cuda_cores: 5120
          architecture: Volta
          uuid: GPU-de33e22d-227e-433b-d5e6-ddc9f7511a17
        - name: Tesla V100-SXM2-32GB
          memory_total: '34359738368'
          cuda_cores: 5120
          architecture: Volta
          uuid: GPU-25a407ad-6bdc-7df3-90b1-3cc506696564
        - name: Tesla V100-SXM2-32GB
          memory_total: '34359738368'
          cuda_cores: 5120
          architecture: Volta
          uuid: GPU-4f64b625-92a7-a5fc-8707-2be5dd87935c
        - name: Tesla V100-SXM2-32GB
          memory_total: '34359738368'
          cuda_cores: 5120
          architecture: Volta
          uuid: GPU-7b00f3c4-c148-f783-18b2-56c4aef00355
        cuda_version: '13.0'
        slurm:
          tres_per_task: cpu:10
          job_name: test_flow
          job_qos: qos_gpu-t3
          stepid: '0'
          conf: /etc/slurm/slurm.conf
          srun_comm_host: 10.148.0.41
          threads_per_core: '1'
          task_pid: '458044'
          nodeid: '0'
          job_partition: gpu_p13
          cpu_bind_type: 'mask_cpu:'
          cluster_name: jean-zay
          launch_node_ipaddr: 10.148.0.41
          job_end_time: '1786974782'
          nodelist: r7i0n2
          step_id: '0'
          distribution: cyclic
          step_num_tasks: '1'
          gpus_on_node: '4'
          procid: '0'
          jobid: '1044842'
          job_id: '1044842'
          job_account: prk@v100
          ntasks_per_node: '1'
          job_uid: '306828'
          topology_addr_pattern: node
          step_num_nodes: '1'
          umask: '0027'
          localid: '0'
          step_nodelist: r7i0n2
          prio_process: '0'
          step_gpus: 0,1,2,3
          nprocs: '1'
          tasks_per_node: '1'
          topology_addr: r7i0n2
          srun_comm_port: '61473'
          spank_gpu_srange_src: default
          spank_gpu_srange: 0-1980
          gtids: '0'
          mem_per_cpu: '4000'
          cpus_on_node: '20'
          script_context: prolog_task
          job_user: ugd35xy
          cpu_bind: quiet,mask_cpu:0x00000000000001F0001F
          nnodes: '1'
          step_launcher_port: '61473'
          job_cpus_per_node: '10'
          job_start_time: '1786953182'
          job_num_nodes: '1'
          cpu_bind_verbose: quiet
          submit_host: jean-zay1
          step_tasks_per_node: '1'
          submit_dir: /lustre/fswork/projects/rech/prk/ugd35xy/Train-AE
          step_resv_ports: 15760-15761
          job_gid: '305299'
          ntasks: '1'
          job_nodelist: r7i0n2
          job_gpus: 0,1,2,3
          cpu_bind_list: '0x00000000000001F0001F'
          cpus_per_task: '10'
          hint: nomultithread
        writer_id: ppqslybakwfb4bu9tj32ly2pg1dsqe06
ae_run_dir:
  desc: null
  value: Student-1_i1pf186a
ae_epoch:
  desc: null
  value: 2000
flow_type:
  desc: null
  value: RealNVP
flow_layers:
  desc: null
  value: 4
latent_dim:
  desc: null
  value:
  - 1
  - 4
  - 4
cond_dim:
  desc: null
  value: null
bijector:
  desc: null
  value: affine
nn_width:
  desc: null
  value: 128
nn_depth:
  desc: null
  value: 2
knots:
  desc: null
  value: 28
interval:
  desc: null
  value: 5.5
learning_rate:
  desc: null
  value: 5.0e-05
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 800
log_freq:
  desc: null
  value: 10
