_wandb:
  cli_version: 0.27.0
  e:
    rkrvzkxobk5vlvowgl4sc9jsocur3les:
      cpu_count: 40
      cpu_count_logical: 80
      cuda_version: '13.0'
      disk:
        /:
          total: '100275146752'
          used: '9929048064'
      executable: /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/python-3.12.7/bin/python
      gpu_count: 4
      gpu_nvidia:
      - architecture: Volta
        cuda_cores: 5120
        memory_total: '34359738368'
        name: Tesla V100-SXM2-32GB
        uuid: GPU-8a0bb359-7bbd-210a-44e1-9edc281dd639
      - architecture: Volta
        cuda_cores: 5120
        memory_total: '34359738368'
        name: Tesla V100-SXM2-32GB
        uuid: GPU-e8328fc2-b4e6-e437-92d2-065550c6533d
      - architecture: Volta
        cuda_cores: 5120
        memory_total: '34359738368'
        name: Tesla V100-SXM2-32GB
        uuid: GPU-f7f4b40c-ff12-2151-a14d-3ba5afe57226
      - architecture: Volta
        cuda_cores: 5120
        memory_total: '34359738368'
        name: Tesla V100-SXM2-32GB
        uuid: GPU-b25cbf30-c39a-440e-ae22-2233778d4cd5
      gpu_type: Tesla V100-SXM2-32GB
      host: r7i7n7
      memory:
        total: '200550293504'
      os: Linux-5.14.0-570.131.1.el9_6.x86_64-x86_64-with-glibc2.34
      program: -m experiments.train_flow
      python: CPython 3.12.7
      root: /lustre/fsn1/projects/rech/prk/ugd35xy/pshear/cosmos
      slurm:
        cluster_name: jean-zay
        conf: /etc/slurm/slurm.conf
        cpu_bind: quiet,mask_cpu:0x00000000000001F0001F
        cpu_bind_list: '0x00000000000001F0001F'
        cpu_bind_type: 'mask_cpu:'
        cpu_bind_verbose: quiet
        cpus_on_node: '20'
        cpus_per_task: '10'
        distribution: cyclic
        gpus_on_node: '4'
        gtids: '0'
        hint: nomultithread
        job_account: prk@v100
        job_cpus_per_node: '10'
        job_end_time: '1788801746'
        job_gid: '305299'
        job_gpus: 0,1,2,3
        job_group: gencvz01
        job_id: '1850267'
        job_name: test_flow
        job_nodelist: r7i7n7
        job_num_nodes: '1'
        job_partition: gpu_p13
        job_qos: qos_gpu-t3
        job_start_time: '1788780146'
        job_uid: '306828'
        job_user: ugd35xy
        jobid: '1850267'
        launch_node_ipaddr: 10.148.0.109
        localid: '0'
        mem_per_cpu: '4000'
        nnodes: '1'
        nodeid: '0'
        nodelist: r7i7n7
        nprocs: '1'
        ntasks: '1'
        ntasks_per_node: '1'
        oom_kill_step: '0'
        prio_process: '0'
        procid: '0'
        script_context: prolog_task
        spank_gpu_srange: 0-1980
        spank_gpu_srange_src: default
        srun_comm_host: 10.148.0.109
        srun_comm_port: '62388'
        step_gpus: 0,1,2,3
        step_id: '0'
        step_launcher_port: '62388'
        step_nodelist: r7i7n7
        step_num_nodes: '1'
        step_num_tasks: '1'
        step_resv_ports: 13513-13514
        step_tasks_per_node: '1'
        stepid: '0'
        submit_dir: /lustre/fswork/projects/rech/prk/ugd35xy/Train-AE
        submit_host: jean-zay2
        task_pid: '216564'
        tasks_per_node: '1'
        threads_per_core: '1'
        topology_addr: r7i7n7
        topology_addr_pattern: node
        tres_per_task: cpu=10
        umask: '0027'
      started_at: '2026-09-07T11:26:10.160929Z'
      writer_id: rkrvzkxobk5vlvowgl4sc9jsocur3les
  framework: torch
  is_jupyter_run: false
  is_kaggle_kernel: false
  python_version: 3.12.7
  start_time: 1788780378
  t:
    1:
    - 1
    - 12
    - 49
    - 51
    2:
    - 1
    - 12
    - 49
    - 51
    3:
    - 2
    - 3
    - 4
    - 13
    - 14
    - 16
    - 42
    4: 3.12.7
    5: 0.27.0
    13: linux-x86_64
ae_epoch: 2000
ae_run_dir: Student-1_i344nq38
batch_size: 256
bijector: affine
cond_dim: null
end_learning_rate: 1.0e-06
epochs: 500
flow_layers: 4
flow_type: RealNVP
interval: 5.5
knots: 28
latent_dim:
- 1
- 4
- 4
log_freq: 10
nn_depth: 2
nn_width: 128
peak_learning_rate: 0.0001
wandb_version: 1
