_wandb:
  cli_version: 0.27.0
  e:
    ppqslybakwfb4bu9tj32ly2pg1dsqe06:
      cpu_count: 40
      cpu_count_logical: 80
      cuda_version: '13.0'
      disk:
        /:
          total: '100275138560'
          used: '9934614528'
      executable: /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/python-3.12.7/bin/python
      gpu_count: 4
      gpu_nvidia:
      - architecture: Volta
        cuda_cores: 5120
        memory_total: '34359738368'
        name: Tesla V100-SXM2-32GB
        uuid: GPU-de33e22d-227e-433b-d5e6-ddc9f7511a17
      - architecture: Volta
        cuda_cores: 5120
        memory_total: '34359738368'
        name: Tesla V100-SXM2-32GB
        uuid: GPU-25a407ad-6bdc-7df3-90b1-3cc506696564
      - architecture: Volta
        cuda_cores: 5120
        memory_total: '34359738368'
        name: Tesla V100-SXM2-32GB
        uuid: GPU-4f64b625-92a7-a5fc-8707-2be5dd87935c
      - architecture: Volta
        cuda_cores: 5120
        memory_total: '34359738368'
        name: Tesla V100-SXM2-32GB
        uuid: GPU-7b00f3c4-c148-f783-18b2-56c4aef00355
      gpu_type: Tesla V100-SXM2-32GB
      host: r7i0n2
      memory:
        total: '200550277120'
      os: Linux-5.14.0-570.116.1.el9_6.x86_64-x86_64-with-glibc2.34
      program: -m experiments.train_flow
      python: CPython 3.12.7
      root: /lustre/fsn1/projects/rech/prk/ugd35xy/pshear/cosmos
      slurm:
        cluster_name: jean-zay
        conf: /etc/slurm/slurm.conf
        cpu_bind: quiet,mask_cpu:0x00000000000001F0001F
        cpu_bind_list: '0x00000000000001F0001F'
        cpu_bind_type: 'mask_cpu:'
        cpu_bind_verbose: quiet
        cpus_on_node: '20'
        cpus_per_task: '10'
        distribution: cyclic
        gpus_on_node: '4'
        gtids: '0'
        hint: nomultithread
        job_account: prk@v100
        job_cpus_per_node: '10'
        job_end_time: '1786974782'
        job_gid: '305299'
        job_gpus: 0,1,2,3
        job_id: '1044842'
        job_name: test_flow
        job_nodelist: r7i0n2
        job_num_nodes: '1'
        job_partition: gpu_p13
        job_qos: qos_gpu-t3
        job_start_time: '1786953182'
        job_uid: '306828'
        job_user: ugd35xy
        jobid: '1044842'
        launch_node_ipaddr: 10.148.0.41
        localid: '0'
        mem_per_cpu: '4000'
        nnodes: '1'
        nodeid: '0'
        nodelist: r7i0n2
        nprocs: '1'
        ntasks: '1'
        ntasks_per_node: '1'
        prio_process: '0'
        procid: '0'
        script_context: prolog_task
        spank_gpu_srange: 0-1980
        spank_gpu_srange_src: default
        srun_comm_host: 10.148.0.41
        srun_comm_port: '61473'
        step_gpus: 0,1,2,3
        step_id: '0'
        step_launcher_port: '61473'
        step_nodelist: r7i0n2
        step_num_nodes: '1'
        step_num_tasks: '1'
        step_resv_ports: 15760-15761
        step_tasks_per_node: '1'
        stepid: '0'
        submit_dir: /lustre/fswork/projects/rech/prk/ugd35xy/Train-AE
        submit_host: jean-zay1
        task_pid: '458044'
        tasks_per_node: '1'
        threads_per_core: '1'
        topology_addr: r7i0n2
        topology_addr_pattern: node
        tres_per_task: cpu:10
        umask: '0027'
      started_at: '2026-08-17T07:57:12.700203Z'
      writer_id: ppqslybakwfb4bu9tj32ly2pg1dsqe06
  framework: torch
  is_jupyter_run: false
  is_kaggle_kernel: false
  python_version: 3.12.7
  start_time: 1786953441
  t:
    1:
    - 1
    - 12
    - 49
    - 51
    2:
    - 1
    - 12
    - 49
    - 51
    3:
    - 2
    - 3
    - 4
    - 13
    - 14
    - 16
    - 42
    4: 3.12.7
    5: 0.27.0
    13: linux-x86_64
ae_epoch: 2000
ae_run_dir: Student-1_i1pf186a
batch_size: 256
bijector: affine
cond_dim: null
epochs: 800
flow_layers: 4
flow_type: RealNVP
interval: 5.5
knots: 28
latent_dim:
- 1
- 4
- 4
learning_rate: 5.0e-05
log_freq: 10
nn_depth: 2
nn_width: 128
wandb_version: 1
